### ISSUE TITLE
Question about Data Augmentation

### ISSUE THREAD

**Issue by zachzhang07** [MathLee/MCCNet#1]
Hello and thanks for your brilliant work!
I am a bit confused about Data Augmentation part. 
In paper it said 
> During the network training, each optical RSI is resized to 256×256 and augmented by **flipping and rotation**, producing seven additional training samples.

BUT in code I find there are no augmentation used in data preparation like:
```
def __getitem__(self, index):
      image = self.rgb_loader(self.images[index])
      gt = self.binary_loader(self.gts[index])
      edge = self.binary_loader(self.edges[index])
      # image,gt =cv_random_flip(image,gt)
      # image,gt =randomCrop(image, gt)
      # image,gt =randomRotation(image, gt)
      # image=colorEnhance(image)
      # gt=randomPeper(gt)
      image = self.img_transform(image)
      gt = self.gt_transform(gt)
      edge = self.gt_transform(edge)
      return image, gt, edge
```

**Comment by MathLee** [comment]
Thank you for your mail. We use the attached code for augmentation. Hope it can solve your problem.




--

Best regards,

Gongyang
PhD ***@***.*** IVP Lab
E-mail: ***@***.***
            ***@***.***




在 2021-12-06 21:43:57，"zachzhang07" ***@***.***> 写道：

Hello and thanks for your brilliant work!
I am a bit confused about Data Augmentation part.
In paper it said

During the network training, each optical RSI is resized to 256×256 and augmented by flipping and rotation, producing seven additional training samples.

BUT in code I find there are no augmentation used in data preparation like:

def __getitem__(self, index):

      image = self.rgb_loader(self.images[index])

      gt = self.binary_loader(self.gts[index])

      edge = self.binary_loader(self.edges[index])

      # image,gt =cv_random_flip(image,gt)

      # image,gt =randomCrop(image, gt)

      # image,gt =randomRotation(image, gt)

      # image=colorEnhance(image)

      # gt=randomPeper(gt)

      image = self.img_transform(image)

      gt = self.gt_transform(gt)

      edge = self.gt_transform(edge)

      return image, gt, edge

**Comment by zachzhang07** [comment]
So these code which is commented should actually be used?
```
      # image,gt =cv_random_flip(image,gt)
      # image,gt =randomCrop(image, gt)
      # image,gt =randomRotation(image, gt)
      # image=colorEnhance(image)
      # gt=randomPeper(gt)
```

**Comment by MathLee** [comment]
We use https://github.com/MathLee/MCCNet/blob/main/data_aug.m for date augmentation, not the code you sent us.




--

Best regards,

Gongyang




在 2021-12-06 22:10:27，"zachzhang07" ***@***.***> 写道：

So these code which is commented should actually be used?

      # image,gt =cv_random_flip(image,gt)
      # image,gt =randomCrop(image, gt)
      # image,gt =randomRotation(image, gt)
      # image=colorEnhance(image)
      # gt=randomPeper(gt)

**Comment by zachzhang07** [comment]
I didn't see the attached file before and sorry for the misunderstanding. 
Thanks for your reply!
